//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrypCloud.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrypCloud.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        public static string _AbortBtn {
            get {
                return ResourceManager.GetString("_AbortBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string _BackBtn {
            get {
                return ResourceManager.GetString("_BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection to server. Please wait ähnelt.
        /// </summary>
        public static string _Connecting_label {
            get {
                return ResourceManager.GetString("_Connecting_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went wrong :( ähnelt.
        /// </summary>
        public static string _ConnectingError {
            get {
                return ResourceManager.GetString("_ConnectingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your account data below. ähnelt.
        /// </summary>
        public static string _CreateAccount_enterAccountData {
            get {
                return ResourceManager.GetString("_CreateAccount_enterAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account successfully requested ähnelt.
        /// </summary>
        public static string _CreateAccount_successHeader {
            get {
                return ResourceManager.GetString("_CreateAccount_successHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your new account was requested successfully. ähnelt.
        /// </summary>
        public static string _CreateAccount_successText {
            get {
                return ResourceManager.GetString("_CreateAccount_successText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new account  ähnelt.
        /// </summary>
        public static string _CreateAccount_Title {
            get {
                return ResourceManager.GetString("_CreateAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description:  ähnelt.
        /// </summary>
        public static string _CreateJob_Description_label {
            get {
                return ResourceManager.GetString("_CreateJob_Description_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new job ähnelt.
        /// </summary>
        public static string _CreateJob_Header {
            get {
                return ResourceManager.GetString("_CreateJob_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name:  ähnelt.
        /// </summary>
        public static string _CreateJob_Name_label {
            get {
                return ResourceManager.GetString("_CreateJob_Name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload ähnelt.
        /// </summary>
        public static string _CreateJob_uploadBtn {
            get {
                return ResourceManager.GetString("_CreateJob_uploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to workspace:  ähnelt.
        /// </summary>
        public static string _CreateJob_WorkspacePath_label {
            get {
                return ResourceManager.GetString("_CreateJob_WorkspacePath_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email:  ähnelt.
        /// </summary>
        public static string _Email_label {
            get {
                return ResourceManager.GetString("_Email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the verification code. ähnelt.
        /// </summary>
        public static string _enterVerificationCode {
            get {
                return ResourceManager.GetString("_enterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitmask: ähnelt.
        /// </summary>
        public static string _JobList_bitmask {
            get {
                return ResourceManager.GetString("_JobList_bitmask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string _JobList_btn_createNew {
            get {
                return ResourceManager.GetString("_JobList_btn_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string _JobList_btn_delete {
            get {
                return ResourceManager.GetString("_JobList_btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string _JobList_btn_open {
            get {
                return ResourceManager.GetString("_JobList_btn_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string _JobList_btn_refresh {
            get {
                return ResourceManager.GetString("_JobList_btn_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creator ähnelt.
        /// </summary>
        public static string _JobList_col_Creator {
            get {
                return ResourceManager.GetString("_JobList_col_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job ID ähnelt.
        /// </summary>
        public static string _JobList_col_Id {
            get {
                return ResourceManager.GetString("_JobList_col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string _JobList_col_Name {
            get {
                return ResourceManager.GetString("_JobList_col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress ähnelt.
        /// </summary>
        public static string _JobList_col_Progress {
            get {
                return ResourceManager.GetString("_JobList_col_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Jobs ähnelt.
        /// </summary>
        public static string _JobList_Header {
            get {
                return ResourceManager.GetString("_JobList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        public static string _JobList_jobDescription {
            get {
                return ResourceManager.GetString("_JobList_jobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string _JobList_jobName {
            get {
                return ResourceManager.GetString("_JobList_jobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        public static string _Login_btn_connect {
            get {
                return ResourceManager.GetString("_Login_btn_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CrypCloud ähnelt.
        /// </summary>
        public static string _Login_header {
            get {
                return ResourceManager.GetString("_Login_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new account ähnelt.
        /// </summary>
        public static string _Login_link_createNewAccount {
            get {
                return ResourceManager.GetString("_Login_link_createNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot Password ähnelt.
        /// </summary>
        public static string _Login_link_ForgotPassword {
            get {
                return ResourceManager.GetString("_Login_link_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A P2P based volunteer cloud solution ähnelt.
        /// </summary>
        public static string _Login_subheader {
            get {
                return ResourceManager.GetString("_Login_subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string _NextBtn {
            get {
                return ResourceManager.GetString("_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm:  ähnelt.
        /// </summary>
        public static string _Password_confirm_label {
            get {
                return ResourceManager.GetString("_Password_confirm_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password:  ähnelt.
        /// </summary>
        public static string _Password_label {
            get {
                return ResourceManager.GetString("_Password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your account data below to reset your password. ähnelt.
        /// </summary>
        public static string _ResetPW_enterData {
            get {
                return ResourceManager.GetString("_ResetPW_enterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We have send an verification email to the email address of the account. Please enter the verification code and your new password below. ähnelt.
        /// </summary>
        public static string _ResetPW_enterVerificationData {
            get {
                return ResourceManager.GetString("_ResetPW_enterVerificationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Password ähnelt.
        /// </summary>
        public static string _ResetPW_Header {
            get {
                return ResourceManager.GetString("_ResetPW_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password Reset Successful ähnelt.
        /// </summary>
        public static string _ResetPW_successHeader {
            get {
                return ResourceManager.GetString("_ResetPW_successHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password has been reset. You may now login with your new password. ähnelt.
        /// </summary>
        public static string _ResetPW_successText {
            get {
                return ResourceManager.GetString("_ResetPW_successText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Type : ähnelt.
        /// </summary>
        public static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name:  ähnelt.
        /// </summary>
        public static string _Username_label {
            get {
                return ResourceManager.GetString("_Username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verification Code:  ähnelt.
        /// </summary>
        public static string _verificationCode_label {
            get {
                return ResourceManager.GetString("_verificationCode_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify ähnelt.
        /// </summary>
        public static string _VerifyBtn {
            get {
                return ResourceManager.GetString("_VerifyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace : ähnelt.
        /// </summary>
        public static string _WorkspacePath {
            get {
                return ResourceManager.GetString("_WorkspacePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap connected {
            get {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disconnected {
            get {
                object obj = ResourceManager.GetObject("disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CrypCloud ähnelt.
        /// </summary>
        public static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A P2P based volunteer cloud solution ähnelt.
        /// </summary>
        public static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout failed. Please stop all running Jobs. ähnelt.
        /// </summary>
        public static string Stop_Running_Jobs_Before_Logout {
            get {
                return ResourceManager.GetString("Stop_Running_Jobs_Before_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CrypCloud ähnelt.
        /// </summary>
        public static string Tab_Caption {
            get {
                return ResourceManager.GetString("Tab_Caption", resourceCulture);
            }
        }
    }
}
