//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptool.VigenereAnalyser.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptool.VigenereAnalyser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method of column analysis ähnelt.
        /// </summary>
        internal static string ColumnAnalysisCaption {
            get {
                return ResourceManager.GetString("ColumnAnalysisCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use most frequent letter ähnelt.
        /// </summary>
        internal static string ColumnAnalysisList1 {
            get {
                return ResourceManager.GetString("ColumnAnalysisList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use sum of squares ähnelt.
        /// </summary>
        internal static string ColumnAnalysisList2 {
            get {
                return ResourceManager.GetString("ColumnAnalysisList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the method of analysis of the ciphertext columns ähnelt.
        /// </summary>
        internal static string ColumnAnalysisTooltip {
            get {
                return ResourceManager.GetString("ColumnAnalysisTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Index of coincidence ähnelt.
        /// </summary>
        internal static string EICCaption {
            get {
                return ResourceManager.GetString("EICCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjust the expected index of coincidence ähnelt.
        /// </summary>
        internal static string EICTooltip {
            get {
                return ResourceManager.GetString("EICTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Letter Frequency of a language ähnelt.
        /// </summary>
        internal static string ELFCaption {
            get {
                return ResourceManager.GetString("ELFCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string ELFList1 {
            get {
                return ResourceManager.GetString("ELFList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string ELFList2 {
            get {
                return ResourceManager.GetString("ELFList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die French ähnelt.
        /// </summary>
        internal static string ELFList3 {
            get {
                return ResourceManager.GetString("ELFList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spanish ähnelt.
        /// </summary>
        internal static string ELFList4 {
            get {
                return ResourceManager.GetString("ELFList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italian ähnelt.
        /// </summary>
        internal static string ELFList5 {
            get {
                return ResourceManager.GetString("ELFList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portugeese ähnelt.
        /// </summary>
        internal static string ELFList6 {
            get {
                return ResourceManager.GetString("ELFList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Null hypothesis for the Chi-square statistic ähnelt.
        /// </summary>
        internal static string ELFTooltip {
            get {
                return ResourceManager.GetString("ELFTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String ähnelt.
        /// </summary>
        internal static string FrequencyOutputCaption {
            get {
                return ResourceManager.GetString("FrequencyOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cipher text divided into columns. Number of columns (strings) equals keylength. ähnelt.
        /// </summary>
        internal static string FrequencyOutputTooltip {
            get {
                return ResourceManager.GetString("FrequencyOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String ähnelt.
        /// </summary>
        internal static string FrequencyStatsCaption {
            get {
                return ResourceManager.GetString("FrequencyStatsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please only connect to the text output of the Frequency Test. ähnelt.
        /// </summary>
        internal static string FrequencyStatsTooltip {
            get {
                return ResourceManager.GetString("FrequencyStatsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double precission floating point value. ähnelt.
        /// </summary>
        internal static string FriedmanInputCaption {
            get {
                return ResourceManager.GetString("FriedmanInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keylength as proposed by the Friedman Test. ähnelt.
        /// </summary>
        internal static string FriedmanInputTooltip {
            get {
                return ResourceManager.GetString("FriedmanInputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method of keylength analysis ähnelt.
        /// </summary>
        internal static string InternalKeyLengthAnalysisCaption {
            get {
                return ResourceManager.GetString("InternalKeyLengthAnalysisCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the internal or external method for analysis of the keylength ähnelt.
        /// </summary>
        internal static string InternalKeyLengthAnalysisTooltip {
            get {
                return ResourceManager.GetString("InternalKeyLengthAnalysisTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integer Array. ähnelt.
        /// </summary>
        internal static string KasiskiInputCaption {
            get {
                return ResourceManager.GetString("KasiskiInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Array contains keylengths as proposed by the Kasiski Test. ähnelt.
        /// </summary>
        internal static string KasiskiInputTooltip {
            get {
                return ResourceManager.GetString("KasiskiInputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integer Array. ähnelt.
        /// </summary>
        internal static string KeywordOutputCaption {
            get {
                return ResourceManager.GetString("KeywordOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword represented as an integer Array. ähnelt.
        /// </summary>
        internal static string KeywordOutputTooltip {
            get {
                return ResourceManager.GetString("KeywordOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum Keylength ähnelt.
        /// </summary>
        internal static string Max_KeylengthCaption {
            get {
                return ResourceManager.GetString("Max_KeylengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter maximum keylength to be analysed by the &apos;Sampled Index of coincidence&apos; method. default = 15 ähnelt.
        /// </summary>
        internal static string Max_KeylengthTooltip {
            get {
                return ResourceManager.GetString("Max_KeylengthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vigenere Analyser ähnelt.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyses a cipher text encrypted using the Vigenère cipher. Output is the keyword of the Vigènere cipher ähnelt.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Input ähnelt.
        /// </summary>
        internal static string StringInputCaption {
            get {
                return ResourceManager.GetString("StringInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cipher text encrypted with the Vigenère cipher. ähnelt.
        /// </summary>
        internal static string StringInputTooltip {
            get {
                return ResourceManager.GetString("StringInputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text output ähnelt.
        /// </summary>
        internal static string StringOutputCaption {
            get {
                return ResourceManager.GetString("StringOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword of the cipher which was used to encrypt the input text.  ähnelt.
        /// </summary>
        internal static string StringOutputTooltip {
            get {
                return ResourceManager.GetString("StringOutputTooltip", resourceCulture);
            }
        }
    }
}
