//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startcenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startcenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       Search.
        /// </summary>
        internal static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recently opened file list..
        /// </summary>
        internal static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the distributed computing platform..
        /// </summary>
        internal static string Connect_to_the_distributed_computing_platform_ {
            get {
                return ResourceManager.GetString("Connect_to_the_distributed_computing_platform_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new workspace with the graphical editor..
        /// </summary>
        internal static string Create_a_new_workspace_with_the_graphical_editor_ {
            get {
                return ResourceManager.GetString("Create_a_new_workspace_with_the_graphical_editor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading RSS Feed.
        /// </summary>
        internal static string LoadingRSSFeed {
            get {
                return ResourceManager.GetString("LoadingRSSFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Functions.
        /// </summary>
        internal static string MainFunctions {
            get {
                return ResourceManager.GetString("MainFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startcenter.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PluginDescriptionURL {
            get {
                return ResourceManager.GetString("PluginDescriptionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access the main functions in the Startcenter.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the online documentation..
        /// </summary>
        internal static string Read_the_online_documentation_ {
            get {
                return ResourceManager.GetString("Read_the_online_documentation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Opened Files.
        /// </summary>
        internal static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this welcome screen at CrypTool 2.0 startup..
        /// </summary>
        internal static string Show_this_welcome_screen_at_CrypTool_2_0_startup_ {
            get {
                return ResourceManager.GetString("Show_this_welcome_screen_at_CrypTool_2_0_startup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a standalone component..
        /// </summary>
        internal static string This_is_a_standalone_component_ {
            get {
                return ResourceManager.GetString("This_is_a_standalone_component_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a project template..
        /// </summary>
        internal static string This_is_a_template {
            get {
                return ResourceManager.GetString("This_is_a_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a workspace editor file..
        /// </summary>
        internal static string This_is_a_WorkspaceManager_file_ {
            get {
                return ResourceManager.GetString("This_is_a_WorkspaceManager_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a project file of the deprecated AnotherEditor..
        /// </summary>
        internal static string This_is_an_AnotherEditor_file_ {
            get {
                return ResourceManager.GetString("This_is_an_AnotherEditor_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the wizard to easily try some CrypTool 2.0 features..
        /// </summary>
        internal static string Use_the_wizard_to_easily_try_some_CrypTool_2_0_features_ {
            get {
                return ResourceManager.GetString("Use_the_wizard_to_easily_try_some_CrypTool_2_0_features_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the official CrypTool 2.0 website..
        /// </summary>
        internal static string Visit_the_official_CrypTool_2_0_website_ {
            get {
                return ResourceManager.GetString("Visit_the_official_CrypTool_2_0_website_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CrypTool 2. A good way to start is either to click on the wizard button in the section “Main Functions” (to get a guided tour) or to load one of the pre-defined templates (which demonstrate the functionality of CrypTool 2 in well-defined cryptographic scenarios)..
        /// </summary>
        internal static string Welcome_to_CrypTool_2_0 {
            get {
                return ResourceManager.GetString("Welcome_to_CrypTool_2_0", resourceCulture);
            }
        }
    }
}
