//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;survey version=&quot;123&quot;&gt;
        ///	&lt;questions&gt;
        ///			&lt;question id=&quot;1&quot;&gt;
        ///				&lt;text lang=&quot;de&quot;&gt;question1DE&lt;/text&gt;
        ///				&lt;text lang=&quot;en&quot;&gt;question1EN&lt;/text&gt;
        ///				&lt;help lang=&quot;de&quot;&gt;question1DEHelp&lt;/help&gt;
        ///				&lt;help lang=&quot;en&quot;&gt;question1ENHelp&lt;/help&gt;
        ///				&lt;answers type=&quot;Rage&quot; from=0 to=10/&gt;
        ///			&lt;/question&gt;
        ///			&lt;question id=&quot;2&quot;&gt;
        ///				&lt;text lang=&quot;de&quot;&gt;question2DE&lt;/text&gt;
        ///				&lt;text lang=&quot;en&quot;&gt;question2EN&lt;/text&gt;
        ///				&lt;help lang=&quot;de&quot;&gt;question2DEHelp&lt;/help&gt;
        ///				&lt;help lang=&quot;en&quot;&gt;question2ENHelp&lt;/help&gt;
        ///				&lt;answers type=&quot;number&quot; from=0 to= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surveyTestQuestions {
            get {
                return ResourceManager.GetString("surveyTestQuestions", resourceCulture);
            }
        }
    }
}
