//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisMonoalphabeticSubstitution.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalysisMonoalphabeticSubstitution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced settings ähnelt.
        /// </summary>
        internal static string AdvancedSettingsGroup {
            get {
                return ResourceManager.GetString("AdvancedSettingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet ähnelt.
        /// </summary>
        internal static string AlphabetCaption {
            get {
                return ResourceManager.GetString("AlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet ähnelt.
        /// </summary>
        internal static string AlphabetGroup {
            get {
                return ResourceManager.GetString("AlphabetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete used alphabet ähnelt.
        /// </summary>
        internal static string AlphabetTooltip {
            get {
                return ResourceManager.GetString("AlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Case sensitive ähnelt.
        /// </summary>
        internal static string CaseSensitiveCaption {
            get {
                return ResourceManager.GetString("CaseSensitiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distinguish between small and captial letters. ähnelt.
        /// </summary>
        internal static string CaseSensitiveTooltip {
            get {
                return ResourceManager.GetString("CaseSensitiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet ähnelt.
        /// </summary>
        internal static string ChooseAlphabetCaption {
            get {
                return ResourceManager.GetString("ChooseAlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string ChooseAlphabetList1 {
            get {
                return ResourceManager.GetString("ChooseAlphabetList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string ChooseAlphabetList2 {
            get {
                return ResourceManager.GetString("ChooseAlphabetList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        internal static string ChooseAlphabetList3 {
            get {
                return ResourceManager.GetString("ChooseAlphabetList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose alphabet ähnelt.
        /// </summary>
        internal static string ChooseAlphabetTooltip {
            get {
                return ResourceManager.GetString("ChooseAlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ciphertext alphabet ähnelt.
        /// </summary>
        internal static string CTAlphabetCaption {
            get {
                return ResourceManager.GetString("CTAlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ciphertext alphabet ähnelt.
        /// </summary>
        internal static string CTAlphabetGroup {
            get {
                return ResourceManager.GetString("CTAlphabetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete used ciphertext alphabet ähnelt.
        /// </summary>
        internal static string CTAlphabetTooltip {
            get {
                return ResourceManager.GetString("CTAlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Case sensitive ähnelt.
        /// </summary>
        internal static string CTCaseSensitiveCaption {
            get {
                return ResourceManager.GetString("CTCaseSensitiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distinguish between small and captial letters. ähnelt.
        /// </summary>
        internal static string CTCaseSensitiveTooltip {
            get {
                return ResourceManager.GetString("CTCaseSensitiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet ähnelt.
        /// </summary>
        internal static string CTChooseAlphabetCaption {
            get {
                return ResourceManager.GetString("CTChooseAlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose ciphertext alphabet ähnelt.
        /// </summary>
        internal static string CTChooseAlphabetTooltip {
            get {
                return ResourceManager.GetString("CTChooseAlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separator ähnelt.
        /// </summary>
        internal static string DefaultWordSeparatorCaption {
            get {
                return ResourceManager.GetString("DefaultWordSeparatorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter word separator ähnelt.
        /// </summary>
        internal static string DefaultWordSeparatorTooltip {
            get {
                return ResourceManager.GetString("DefaultWordSeparatorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monoalphabetic Substitution Analyzer ähnelt.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cryptanalyze monoalphabetic substitution ciphers ähnelt.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ciphertext alphabet ähnelt.
        /// </summary>
        internal static string PropCiphertextalphabetCaption {
            get {
                return ResourceManager.GetString("PropCiphertextalphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet of the ciphertext ähnelt.
        /// </summary>
        internal static string PropCiphertextalphabetTooltip {
            get {
                return ResourceManager.GetString("PropCiphertextalphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ciphertext ähnelt.
        /// </summary>
        internal static string PropCiphertextCaption {
            get {
                return ResourceManager.GetString("PropCiphertextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encrypted text ähnelt.
        /// </summary>
        internal static string PropCiphertextTooltip {
            get {
                return ResourceManager.GetString("PropCiphertextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictioanry ähnelt.
        /// </summary>
        internal static string PropLanguagedictionaryCaption {
            get {
                return ResourceManager.GetString("PropLanguagedictionaryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictionary of assumed plaintext language ähnelt.
        /// </summary>
        internal static string PropLanguagedictionaryTooltip {
            get {
                return ResourceManager.GetString("PropLanguagedictionaryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext alphabet ähnelt.
        /// </summary>
        internal static string PropPlaintextalphabetCaption {
            get {
                return ResourceManager.GetString("PropPlaintextalphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext alphabet ähnelt.
        /// </summary>
        internal static string PropPlaintextalphabetoutputCaption {
            get {
                return ResourceManager.GetString("PropPlaintextalphabetoutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext alphabet with letters in the order to decrypt the ciphertext ähnelt.
        /// </summary>
        internal static string PropPlaintextalphabetoutputTooltip {
            get {
                return ResourceManager.GetString("PropPlaintextalphabetoutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assumed alphabet of the plaintext ähnelt.
        /// </summary>
        internal static string PropPlaintextalphabetTooltip {
            get {
                return ResourceManager.GetString("PropPlaintextalphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext ähnelt.
        /// </summary>
        internal static string PropPlaintextCaption {
            get {
                return ResourceManager.GetString("PropPlaintextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrypted text ähnelt.
        /// </summary>
        internal static string PropPlaintextTooltip {
            get {
                return ResourceManager.GetString("PropPlaintextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference text ähnelt.
        /// </summary>
        internal static string PropReferencetextCaption {
            get {
                return ResourceManager.GetString("PropReferencetextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample text to extract letter frequencies of the assumed plaintext language ähnelt.
        /// </summary>
        internal static string PropReferencetextTooltip {
            get {
                return ResourceManager.GetString("PropReferencetextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext alphabet ähnelt.
        /// </summary>
        internal static string PTAlphabetCaption {
            get {
                return ResourceManager.GetString("PTAlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext alphabet ähnelt.
        /// </summary>
        internal static string PTAlphabetGroup {
            get {
                return ResourceManager.GetString("PTAlphabetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete used plaintext alphabet ähnelt.
        /// </summary>
        internal static string PTAlphabetTooltip {
            get {
                return ResourceManager.GetString("PTAlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Case sensitive ähnelt.
        /// </summary>
        internal static string PTCaseSensitiveCaption {
            get {
                return ResourceManager.GetString("PTCaseSensitiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distinguish between small and captial letters. ähnelt.
        /// </summary>
        internal static string PTCaseSensitiveTooltip {
            get {
                return ResourceManager.GetString("PTCaseSensitiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet ähnelt.
        /// </summary>
        internal static string PTChooseAlphabetCaption {
            get {
                return ResourceManager.GetString("PTChooseAlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose plaintext alphabet ähnelt.
        /// </summary>
        internal static string PTChooseAlphabetTooltip {
            get {
                return ResourceManager.GetString("PTChooseAlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separate plaintext/ciphertext alphabets ähnelt.
        /// </summary>
        internal static string SeparateAlphabetsCaption {
            get {
                return ResourceManager.GetString("SeparateAlphabetsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use distinct alphabets for plaintext and ciphertext ähnelt.
        /// </summary>
        internal static string SeparateAlphabetsTooltip {
            get {
                return ResourceManager.GetString("SeparateAlphabetsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default word separator ähnelt.
        /// </summary>
        internal static string UseDefaultWordSeparatorCaption {
            get {
                return ResourceManager.GetString("UseDefaultWordSeparatorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use default word separator (blank) for dictionary attack or set manually a separator ähnelt.
        /// </summary>
        internal static string UseDefaultWordSeparatorTooltip {
            get {
                return ResourceManager.GetString("UseDefaultWordSeparatorTooltip", resourceCulture);
            }
        }
    }
}
