//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptool.P2PEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptool.P2PEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        internal static string Account_Activation_ {
            get {
                return ResourceManager.GetString("Account_Activation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Creation.
        /// </summary>
        internal static string Account_Creation_ {
            get {
                return ResourceManager.GetString("Account_Creation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully activated.
        /// </summary>
        internal static string Account_successfully_activated_ {
            get {
                return ResourceManager.GetString("Account_successfully_activated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ActivateButton_ {
            get {
                return ResourceManager.GetString("ActivateButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating account....
        /// </summary>
        internal static string Activating_account_ {
            get {
                return ResourceManager.GetString("Activating_account_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code:.
        /// </summary>
        internal static string Activation_Code_ {
            get {
                return ResourceManager.GetString("Activation_Code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured: {0}.
        /// </summary>
        internal static string An_exception_occured___1 {
            get {
                return ResourceManager.GetString("An_exception_occured___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodownloaded user account data for user &apos;{0}&apos;.
        /// </summary>
        internal static string Autodownloaded_user_account_data_for_user_ {
            get {
                return ResourceManager.GetString("Autodownloaded_user_account_data_for_user_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic created account folder: {0}.
        /// </summary>
        internal static string Automatic_created_account_folder_ {
            get {
                return ResourceManager.GetString("Automatic_created_account_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton_ {
            get {
                return ResourceManager.GetString("BackButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect, account &apos;{0}&apos; not found!.
        /// </summary>
        internal static string Cannot_connect_account_not_found_ {
            get {
                return ResourceManager.GetString("Cannot_connect_account_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect using account &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Cannot_connect_using_account_ {
            get {
                return ResourceManager.GetString("Cannot_connect_using_account_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create default account data directory &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Cannot_create_default_account_data_directory_ {
            get {
                return ResourceManager.GetString("Cannot_create_default_account_data_directory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate authorization required.
        /// </summary>
        internal static string Certificate_authorization_required {
            get {
                return ResourceManager.GetString("Certificate_authorization_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm:.
        /// </summary>
        internal static string Confirm_ {
            get {
                return ResourceManager.GetString("Confirm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectButton_ {
            get {
                return ResourceManager.GetString("ConnectButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the received certificate to your AppData folder:{0}.
        /// </summary>
        internal static string Could_not_save_the_received_certificate_to_your_AppData_folder_ {
            get {
                return ResourceManager.GetString("Could_not_save_the_received_certificate_to_your_AppData_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string Create_a_new_account_ {
            get {
                return ResourceManager.GetString("Create_a_new_account_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrypTool 2.0.
        /// </summary>
        internal static string CrypTool_2_0_ {
            get {
                return ResourceManager.GetString("CrypTool_2_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed Computing Platform.
        /// </summary>
        internal static string Distributed_Computing_Platform_ {
            get {
                return ResourceManager.GetString("Distributed_Computing_Platform_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Email_ {
            get {
                return ResourceManager.GetString("Email_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        internal static string Email_is_not_valid_ {
            get {
                return ResourceManager.GetString("Email_is_not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while autodownloading your account data: {0}.
        /// </summary>
        internal static string Error_while_autodownloading_your_account_data_ {
            get {
                return ResourceManager.GetString("Error_while_autodownloading_your_account_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string Forgot_Password_ {
            get {
                return ResourceManager.GetString("Forgot_Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. To activate your account, you need to validate your email address.
        /// A verification code was sent per email..
        /// </summary>
        internal static string GetNewCertificate_RetrieveCertificate_ {
            get {
                return ResourceManager.GetString("GetNewCertificate_RetrieveCertificate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpTunnel successfully established.
        /// </summary>
        internal static string HttpTunnel_successfully_established_ {
            get {
                return ResourceManager.GetString("HttpTunnel_successfully_established_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured: {0}.
        /// </summary>
        internal static string InvalidCertificateRegistration_Exception_occured___1 {
            get {
                return ResourceManager.GetString("InvalidCertificateRegistration_Exception_occured___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration: {0}.
        /// </summary>
        internal static string InvalidCertificateRegistration_Invalid_registration___1 {
            get {
                return ResourceManager.GetString("InvalidCertificateRegistration_Invalid_registration___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ProtocolVersion. Please update CrypTool 2.0.
        /// </summary>
        internal static string New_ProtocolVersion__Please_update_CrypTool_2_0 {
            get {
                return ResourceManager.GetString("New_ProtocolVersion__Please_update_CrypTool_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account data found for &apos;{0}&apos;. Try to download from server....
        /// </summary>
        internal static string No_account_data_found_for_Try_to_download_from_server_ {
            get {
                return ResourceManager.GetString("No_account_data_found_for_Try_to_download_from_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy server configured. Please check your configuration..
        /// </summary>
        internal static string No_proxy_server_configured__Please_check_your_configuration_ {
            get {
                return ResourceManager.GetString("No_proxy_server_configured__Please_check_your_configuration_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton_ {
            get {
                return ResourceManager.GetString("OKButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string P2PEditor_Tab_Caption {
            get {
                return ResourceManager.GetString("P2PEditor_Tab_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not valid..
        /// </summary>
        internal static string Password_is_not_valid_ {
            get {
                return ResourceManager.GetString("Password_is_not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords did not match..
        /// </summary>
        internal static string Passwords_did_not_match_ {
            get {
                return ResourceManager.GetString("Passwords_did_not_match_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the activation code which you received by email.
        ///Also enter your password. After clicking the activate button your
        ///account data will be stored in your local users folder..
        /// </summary>
        internal static string Please_enter_the_activation_code_ {
            get {
                return ResourceManager.GetString("Please_enter_the_activation_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the data below to request your own personal account (needed for participating in distributed
        ///computing - like distributed key searching). CrypTool 2.0 will connect to our server and request
        ///your account data. This data will be stored into your application data folder of windows.
        ///We will send you an activation code. Use this code to activate your account by clicking the activate button..
        /// </summary>
        internal static string Please_enter_the_data_below_ {
            get {
                return ResourceManager.GetString("Please_enter_the_data_below_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Error &apos;{0}&apos; occured: {1}.
        /// </summary>
        internal static string Proxy_Error_occured_ {
            get {
                return ResourceManager.GetString("Proxy_Error_occured_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Error ({0}) occured:.
        /// </summary>
        internal static string ProxyErrorOccured_Proxy_Error___1__occured_ {
            get {
                return ResourceManager.GetString("ProxyErrorOccured_Proxy_Error___1__occured_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my password.
        /// </summary>
        internal static string Remember_my_password_ {
            get {
                return ResourceManager.GetString("Remember_my_password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RequestButton_ {
            get {
                return ResourceManager.GetString("RequestButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting certificate....
        /// </summary>
        internal static string Requesting_certificate_ {
            get {
                return ResourceManager.GetString("Requesting_certificate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error occurred. Please try again later.
        /// </summary>
        internal static string Server_error_occurred__Please_try_again_later {
            get {
                return ResourceManager.GetString("Server_error_occurred__Please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSLCertificate revoked. Please update CrypTool 2.0..
        /// </summary>
        internal static string SSLCertificate_revoked__Please_update_CrypTool_2_0_ {
            get {
                return ResourceManager.GetString("SSLCertificate_revoked__Please_update_CrypTool_2_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address was not verified.
        ///Please check your email account for an activation code we just sent to you and activate your account..
        /// </summary>
        internal static string The_email_address_was_not_verified_ {
            get {
                return ResourceManager.GetString("The_email_address_was_not_verified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email already exists. Please choose another one..
        /// </summary>
        internal static string The_email_already_exists__Please_choose_another_one_ {
            get {
                return ResourceManager.GetString("The_email_already_exists__Please_choose_another_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username already exists. Please choose another one..
        /// </summary>
        internal static string The_username_already_exists__Please_choose_another_one_ {
            get {
                return ResourceManager.GetString("The_username_already_exists__Please_choose_another_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and email already exist but the entered password was wrong..
        /// </summary>
        internal static string The_username_and_email_already_exist_but_the_entered_password_was_wrong_ {
            get {
                return ResourceManager.GetString("The_username_and_email_already_exist_but_the_entered_password_was_wrong_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a communication problem with the server: {0} 
        ///Please try again later.
        /// </summary>
        internal static string There_was_a_communication_problem_with_the_server {
            get {
                return ResourceManager.GetString("There_was_a_communication_problem_with_the_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Username_ {
            get {
                return ResourceManager.GetString("Username_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid..
        /// </summary>
        internal static string Username_is_not_valid_ {
            get {
                return ResourceManager.GetString("Username_is_not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new account was requested successfully and can be used after verification. 
        ///Press the OK button to proceed..
        /// </summary>
        internal static string Your_new_account_was_requested_successfully_and_can_be_used_after_verification_ {
            get {
                return ResourceManager.GetString("Your_new_account_was_requested_successfully_and_can_be_used_after_verification_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new account was successfully activated and can now be used. 
        ///Press the OK button to proceed..
        /// </summary>
        internal static string Your_new_account_was_successfully_activated_ {
            get {
                return ResourceManager.GetString("Your_new_account_was_successfully_activated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was wrong. We could not autodownload your account data..
        /// </summary>
        internal static string Your_password_was_wrong_We_could_not_autodownload_your_account_data_ {
            get {
                return ResourceManager.GetString("Your_password_was_wrong_We_could_not_autodownload_your_account_data_", resourceCulture);
            }
        }
    }
}
