//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigaba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigaba.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionCaption {
            get {
                return ResourceManager.GetString("ActionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the mode of opertation.
        /// </summary>
        public static string ActionTooltip {
            get {
                return ResourceManager.GetString("ActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case handling.
        /// </summary>
        public static string CaseHandlingCaption {
            get {
                return ResourceManager.GetString("CaseHandlingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve case.
        /// </summary>
        public static string CaseHandlingList1 {
            get {
                return ResourceManager.GetString("CaseHandlingList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to upper.
        /// </summary>
        public static string CaseHandlingList2 {
            get {
                return ResourceManager.GetString("CaseHandlingList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to lower.
        /// </summary>
        public static string CaseHandlingList3 {
            get {
                return ResourceManager.GetString("CaseHandlingList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should be done with upper and lower case letters?.
        /// </summary>
        public static string CaseHandlingTooltip {
            get {
                return ResourceManager.GetString("CaseHandlingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher rotor bank.
        /// </summary>
        public static string CipherGroup {
            get {
                return ResourceManager.GetString("CipherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher key.
        /// </summary>
        public static string CipherKeyCaption {
            get {
                return ResourceManager.GetString("CipherKeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the positions of the cipher rotors.
        /// </summary>
        public static string CipherKeyTooltip {
            get {
                return ResourceManager.GetString("CipherKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher rotor 1 (most right).
        /// </summary>
        public static string CipherRotor1Caption {
            get {
                return ResourceManager.GetString("CipherRotor1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string CipherRotor1ReverseCaption {
            get {
                return ResourceManager.GetString("CipherRotor1ReverseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the typ of the first cipher rotor.
        /// </summary>
        public static string CipherRotor1Tooltip {
            get {
                return ResourceManager.GetString("CipherRotor1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher rotor 2.
        /// </summary>
        public static string CipherRotor2Caption {
            get {
                return ResourceManager.GetString("CipherRotor2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for plug the rotor heads up.
        /// </summary>
        public static string CipherRotor2ReverseTooltip {
            get {
                return ResourceManager.GetString("CipherRotor2ReverseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the typ of the second cipher rotor.
        /// </summary>
        public static string CipherRotor2Tooltip {
            get {
                return ResourceManager.GetString("CipherRotor2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher Rotor 3.
        /// </summary>
        public static string CipherRotor3Caption {
            get {
                return ResourceManager.GetString("CipherRotor3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the third cipher rotor.
        /// </summary>
        public static string CipherRotor3ToolTip {
            get {
                return ResourceManager.GetString("CipherRotor3ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher Rotor 4.
        /// </summary>
        public static string CipherRotor4Caption {
            get {
                return ResourceManager.GetString("CipherRotor4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the fourth cipher rotor.
        /// </summary>
        public static string CipherRotor4Tooltip {
            get {
                return ResourceManager.GetString("CipherRotor4Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher Rotor 5 (most left).
        /// </summary>
        public static string CipherRotor5Caption {
            get {
                return ResourceManager.GetString("CipherRotor5Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the fith cipher rotor.
        /// </summary>
        public static string CipherRotor5Tooltip {
            get {
                return ResourceManager.GetString("CipherRotor5Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control rotor bank.
        /// </summary>
        public static string ControlGroup {
            get {
                return ResourceManager.GetString("ControlGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control key.
        /// </summary>
        public static string ControlKeyCaption {
            get {
                return ResourceManager.GetString("ControlKeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the positions of the control rotors.
        /// </summary>
        public static string ControlKeyTooltip {
            get {
                return ResourceManager.GetString("ControlKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control rotor 1 (most right).
        /// </summary>
        public static string ControlRotor1Caption {
            get {
                return ResourceManager.GetString("ControlRotor1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string ControlRotor1ReverseCaption {
            get {
                return ResourceManager.GetString("ControlRotor1ReverseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the typ of the first control rotor.
        /// </summary>
        public static string ControlRotor1Tooltip {
            get {
                return ResourceManager.GetString("ControlRotor1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control rotor 2.
        /// </summary>
        public static string ControlRotor2Caption {
            get {
                return ResourceManager.GetString("ControlRotor2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for plug in the rotor heads up.
        /// </summary>
        public static string ControlRotor2ReverseTooltip {
            get {
                return ResourceManager.GetString("ControlRotor2ReverseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the typ of the second control rotor.
        /// </summary>
        public static string ControlRotor2Tooltip {
            get {
                return ResourceManager.GetString("ControlRotor2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control rotor 3.
        /// </summary>
        public static string ControlRotor3Caption {
            get {
                return ResourceManager.GetString("ControlRotor3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the third control rotor.
        /// </summary>
        public static string ControlRotor3Tooltip {
            get {
                return ResourceManager.GetString("ControlRotor3Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control rotor 4.
        /// </summary>
        public static string ControlRotor4Caption {
            get {
                return ResourceManager.GetString("ControlRotor4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the fourth control rotor.
        /// </summary>
        public static string ControlRotor4ToolTip {
            get {
                return ResourceManager.GetString("ControlRotor4ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control rotor 5 (most left).
        /// </summary>
        public static string ControlRotor5Caption {
            get {
                return ResourceManager.GetString("ControlRotor5Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the fith control rotor.
        /// </summary>
        public static string ControlRotor5ToolTip {
            get {
                return ResourceManager.GetString("ControlRotor5ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index rotor bank.
        /// </summary>
        public static string IndexGroup {
            get {
                return ResourceManager.GetString("IndexGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index key.
        /// </summary>
        public static string IndexKeyCaption {
            get {
                return ResourceManager.GetString("IndexKeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the positions of the index rotors.
        /// </summary>
        public static string IndexKeyTooltip {
            get {
                return ResourceManager.GetString("IndexKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Rotor 1 (most left).
        /// </summary>
        public static string IndexRotor1Caption {
            get {
                return ResourceManager.GetString("IndexRotor1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the first index rotor.
        /// </summary>
        public static string IndexRotor1Tooltip {
            get {
                return ResourceManager.GetString("IndexRotor1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Rotor 2.
        /// </summary>
        public static string IndexRotor2Caption {
            get {
                return ResourceManager.GetString("IndexRotor2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the second index rotor.
        /// </summary>
        public static string IndexRotor2Tooltip {
            get {
                return ResourceManager.GetString("IndexRotor2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Rotor 3.
        /// </summary>
        public static string IndexRotor3Caption {
            get {
                return ResourceManager.GetString("IndexRotor3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the third index rotor.
        /// </summary>
        public static string IndexRotor3Tooltip {
            get {
                return ResourceManager.GetString("IndexRotor3Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Rotor 4.
        /// </summary>
        public static string IndexRotor4Caption {
            get {
                return ResourceManager.GetString("IndexRotor4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the fourth index rotor.
        /// </summary>
        public static string IndexRotor4Tooltip {
            get {
                return ResourceManager.GetString("IndexRotor4Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Rotor 5  (most right).
        /// </summary>
        public static string IndexRotor5Caption {
            get {
                return ResourceManager.GetString("IndexRotor5Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of the fith index rotor.
        /// </summary>
        public static string IndexRotor5Tooltip {
            get {
                return ResourceManager.GetString("IndexRotor5Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigaba.
        /// </summary>
        public static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American rotor cipher machine.
        /// </summary>
        public static string PluginToolTip {
            get {
                return ResourceManager.GetString("PluginToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string SigabaSettings_SigabaSettings_Cipher {
            get {
                return ResourceManager.GetString("SigabaSettings_SigabaSettings_Cipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string SigabaSettings_SigabaSettings_Decipher {
            get {
                return ResourceManager.GetString("SigabaSettings_SigabaSettings_Decipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text options.
        /// </summary>
        public static string TextOptionsGroup {
            get {
                return ResourceManager.GetString("TextOptionsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown symbol handling.
        /// </summary>
        public static string UnknownSymbolHandlingCaption {
            get {
                return ResourceManager.GetString("UnknownSymbolHandlingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore (leave unmodified).
        /// </summary>
        public static string UnknownSymbolHandlingList1 {
            get {
                return ResourceManager.GetString("UnknownSymbolHandlingList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string UnknownSymbolHandlingList2 {
            get {
                return ResourceManager.GetString("UnknownSymbolHandlingList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with &apos;X&apos;.
        /// </summary>
        public static string UnknownSymbolHandlingList3 {
            get {
                return ResourceManager.GetString("UnknownSymbolHandlingList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should be done with encountered characters at the input which are not in the alphabet?.
        /// </summary>
        public static string UnknownSymbolHandlingTooltip {
            get {
                return ResourceManager.GetString("UnknownSymbolHandlingTooltip", resourceCulture);
            }
        }
    }
}
