//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomInput.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomInput.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByteArray Output.
        /// </summary>
        internal static string ByteArrayOutputCaption {
            get {
                return ResourceManager.GetString("ByteArrayOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte array of given length..
        /// </summary>
        internal static string ByteArrayOutputTooltip {
            get {
                return ResourceManager.GetString("ByteArrayOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string BytesCaption {
            get {
                return ResourceManager.GetString("BytesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of random bytes to be created. (1 - 10496000).
        /// </summary>
        internal static string BytesTooltip {
            get {
                return ResourceManager.GetString("BytesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string KeepRNDCaption {
            get {
                return ResourceManager.GetString("KeepRNDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string KeepRNDList1 {
            get {
                return ResourceManager.GetString("KeepRNDList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string KeepRNDList2 {
            get {
                return ResourceManager.GetString("KeepRNDList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate and keep random bytes only once.
        /// </summary>
        internal static string KeepRNDTooltip {
            get {
                return ResourceManager.GetString("KeepRNDTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number List Output.
        /// </summary>
        internal static string NumberListOutputCaption {
            get {
                return ResourceManager.GetString("NumberListOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of random numbers.
        /// </summary>
        internal static string NumberListOutputTooltip {
            get {
                return ResourceManager.GetString("NumberListOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Output.
        /// </summary>
        internal static string NumberOutputCaption {
            get {
                return ResourceManager.GetString("NumberOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A random number.
        /// </summary>
        internal static string NumberOutputTooltip {
            get {
                return ResourceManager.GetString("NumberOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Numberlist.
        /// </summary>
        internal static string NumNumbersCaption {
            get {
                return ResourceManager.GetString("NumNumbersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many numbers should the number list contain.
        /// </summary>
        internal static string NumNumbersTooltip {
            get {
                return ResourceManager.GetString("NumNumbersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Generator.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple random input generator..
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Output.
        /// </summary>
        internal static string StreamOutputCaption {
            get {
                return ResourceManager.GetString("StreamOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory stream of given length..
        /// </summary>
        internal static string StreamOutputTooltip {
            get {
                return ResourceManager.GetString("StreamOutputTooltip", resourceCulture);
            }
        }
    }
}
