//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptool.Fialka.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptool.Fialka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text.
        /// </summary>
        internal static string InputTextCaption {
            get {
                return ResourceManager.GetString("InputTextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a string to be processed by the Fialka machine..
        /// </summary>
        internal static string InputTextDescription {
            get {
                return ResourceManager.GetString("InputTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fialka machine settings.
        /// </summary>
        internal static string MachineSettings {
            get {
                return ResourceManager.GetString("MachineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string OutputKeyCaption {
            get {
                return ResourceManager.GetString("OutputKeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key settings before end after the encryption..
        /// </summary>
        internal static string OutputKeyDescription {
            get {
                return ResourceManager.GetString("OutputKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output text.
        /// </summary>
        internal static string OutputTextCaption {
            get {
                return ResourceManager.GetString("OutputTextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output a string to be processed by the Fialka machine..
        /// </summary>
        internal static string OutputTextDescription {
            get {
                return ResourceManager.GetString("OutputTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fialka.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyalphabetic rotor-cipher machine.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card.
        /// </summary>
        internal static string PunchCard {
            get {
                return ResourceManager.GetString("PunchCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PunchCard10Caption {
            get {
                return ResourceManager.GetString("PunchCard10Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 10..
        /// </summary>
        internal static string PunchCard10Tooltip {
            get {
                return ResourceManager.GetString("PunchCard10Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string PunchCard11Caption {
            get {
                return ResourceManager.GetString("PunchCard11Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 11..
        /// </summary>
        internal static string PunchCard11Tooltip {
            get {
                return ResourceManager.GetString("PunchCard11Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string PunchCard12Caption {
            get {
                return ResourceManager.GetString("PunchCard12Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 12..
        /// </summary>
        internal static string PunchCard12Tooltip {
            get {
                return ResourceManager.GetString("PunchCard12Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string PunchCard13Caption {
            get {
                return ResourceManager.GetString("PunchCard13Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 13..
        /// </summary>
        internal static string PunchCard13Tooltip {
            get {
                return ResourceManager.GetString("PunchCard13Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string PunchCard14Caption {
            get {
                return ResourceManager.GetString("PunchCard14Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 14..
        /// </summary>
        internal static string PunchCard14Tooltip {
            get {
                return ResourceManager.GetString("PunchCard14Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string PunchCard15Caption {
            get {
                return ResourceManager.GetString("PunchCard15Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 15..
        /// </summary>
        internal static string PunchCard15Tooltip {
            get {
                return ResourceManager.GetString("PunchCard15Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string PunchCard16Caption {
            get {
                return ResourceManager.GetString("PunchCard16Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 16..
        /// </summary>
        internal static string PunchCard16Tooltip {
            get {
                return ResourceManager.GetString("PunchCard16Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string PunchCard17Caption {
            get {
                return ResourceManager.GetString("PunchCard17Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 17..
        /// </summary>
        internal static string PunchCard17Tooltip {
            get {
                return ResourceManager.GetString("PunchCard17Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string PunchCard18Caption {
            get {
                return ResourceManager.GetString("PunchCard18Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 18..
        /// </summary>
        internal static string PunchCard18Tooltip {
            get {
                return ResourceManager.GetString("PunchCard18Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string PunchCard19Caption {
            get {
                return ResourceManager.GetString("PunchCard19Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 19..
        /// </summary>
        internal static string PunchCard19Tooltip {
            get {
                return ResourceManager.GetString("PunchCard19Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        internal static string PunchCard1Caption {
            get {
                return ResourceManager.GetString("PunchCard1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 1..
        /// </summary>
        internal static string PunchCard1Tooltip {
            get {
                return ResourceManager.GetString("PunchCard1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PunchCard20Caption {
            get {
                return ResourceManager.GetString("PunchCard20Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 20..
        /// </summary>
        internal static string PunchCard20Tooltip {
            get {
                return ResourceManager.GetString("PunchCard20Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string PunchCard21Caption {
            get {
                return ResourceManager.GetString("PunchCard21Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 21..
        /// </summary>
        internal static string PunchCard21Tooltip {
            get {
                return ResourceManager.GetString("PunchCard21Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string PunchCard22Caption {
            get {
                return ResourceManager.GetString("PunchCard22Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 22..
        /// </summary>
        internal static string PunchCard22Tooltip {
            get {
                return ResourceManager.GetString("PunchCard22Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string PunchCard23Caption {
            get {
                return ResourceManager.GetString("PunchCard23Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 23..
        /// </summary>
        internal static string PunchCard23Tooltip {
            get {
                return ResourceManager.GetString("PunchCard23Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string PunchCard24Caption {
            get {
                return ResourceManager.GetString("PunchCard24Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 24..
        /// </summary>
        internal static string PunchCard24Tooltip {
            get {
                return ResourceManager.GetString("PunchCard24Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string PunchCard25Caption {
            get {
                return ResourceManager.GetString("PunchCard25Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 25..
        /// </summary>
        internal static string PunchCard25Tooltip {
            get {
                return ResourceManager.GetString("PunchCard25Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string PunchCard26Caption {
            get {
                return ResourceManager.GetString("PunchCard26Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 26..
        /// </summary>
        internal static string PunchCard26Tooltip {
            get {
                return ResourceManager.GetString("PunchCard26Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string PunchCard27Caption {
            get {
                return ResourceManager.GetString("PunchCard27Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 27..
        /// </summary>
        internal static string PunchCard27Tooltip {
            get {
                return ResourceManager.GetString("PunchCard27Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string PunchCard28Caption {
            get {
                return ResourceManager.GetString("PunchCard28Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 28..
        /// </summary>
        internal static string PunchCard28Tooltip {
            get {
                return ResourceManager.GetString("PunchCard28Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string PunchCard29Caption {
            get {
                return ResourceManager.GetString("PunchCard29Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 29..
        /// </summary>
        internal static string PunchCard29Tooltip {
            get {
                return ResourceManager.GetString("PunchCard29Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02.
        /// </summary>
        internal static string PunchCard2Caption {
            get {
                return ResourceManager.GetString("PunchCard2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 2..
        /// </summary>
        internal static string PunchCard2Tooltip {
            get {
                return ResourceManager.GetString("PunchCard2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string PunchCard30Caption {
            get {
                return ResourceManager.GetString("PunchCard30Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 30..
        /// </summary>
        internal static string PunchCard30Tooltip {
            get {
                return ResourceManager.GetString("PunchCard30Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03.
        /// </summary>
        internal static string PunchCard3Caption {
            get {
                return ResourceManager.GetString("PunchCard3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 3..
        /// </summary>
        internal static string PunchCard3Tooltip {
            get {
                return ResourceManager.GetString("PunchCard3Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04.
        /// </summary>
        internal static string PunchCard4Caption {
            get {
                return ResourceManager.GetString("PunchCard4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 4..
        /// </summary>
        internal static string PunchCard4Tooltip {
            get {
                return ResourceManager.GetString("PunchCard4Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05.
        /// </summary>
        internal static string PunchCard5Caption {
            get {
                return ResourceManager.GetString("PunchCard5Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 5..
        /// </summary>
        internal static string PunchCard5Tooltip {
            get {
                return ResourceManager.GetString("PunchCard5Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06.
        /// </summary>
        internal static string PunchCard6Caption {
            get {
                return ResourceManager.GetString("PunchCard6Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 6..
        /// </summary>
        internal static string PunchCard6Tooltip {
            get {
                return ResourceManager.GetString("PunchCard6Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07.
        /// </summary>
        internal static string PunchCard7Caption {
            get {
                return ResourceManager.GetString("PunchCard7Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 7..
        /// </summary>
        internal static string PunchCard7Tooltip {
            get {
                return ResourceManager.GetString("PunchCard7Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08.
        /// </summary>
        internal static string PunchCard8Caption {
            get {
                return ResourceManager.GetString("PunchCard8Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 8..
        /// </summary>
        internal static string PunchCard8Tooltip {
            get {
                return ResourceManager.GetString("PunchCard8Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09.
        /// </summary>
        internal static string PunchCard9Caption {
            get {
                return ResourceManager.GetString("PunchCard9Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch card mapping of contact 9..
        /// </summary>
        internal static string PunchCard9Tooltip {
            get {
                return ResourceManager.GetString("PunchCard9Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set identity .
        /// </summary>
        internal static string ResetPunchCardCaption {
            get {
                return ResourceManager.GetString("ResetPunchCardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the punch card substitution to identity (set the triangle)..
        /// </summary>
        internal static string ResetPunchCardTooltip {
            get {
                return ResourceManager.GetString("ResetPunchCardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null offsets.
        /// </summary>
        internal static string ResetRotorCoreOffsetCaption {
            get {
                return ResourceManager.GetString("ResetRotorCoreOffsetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the rotor core offsets to 0..
        /// </summary>
        internal static string ResetRotorCoreOffsetTooltip {
            get {
                return ResourceManager.GetString("ResetRotorCoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base positions.
        /// </summary>
        internal static string ResetRotorCoreOrderCaption {
            get {
                return ResourceManager.GetString("ResetRotorCoreOrderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order the cores into base positions..
        /// </summary>
        internal static string ResetRotorCoreOrderTooltip {
            get {
                return ResourceManager.GetString("ResetRotorCoreOrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deafult core sides.
        /// </summary>
        internal static string ResetRotorCoreSidesCaption {
            get {
                return ResourceManager.GetString("ResetRotorCoreSidesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the core sides to default values (side 1)..
        /// </summary>
        internal static string ResetRotorCoreSidesTooltip {
            get {
                return ResourceManager.GetString("ResetRotorCoreSidesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base positions.
        /// </summary>
        internal static string ResetRotorOffsetBaseCaption {
            get {
                return ResourceManager.GetString("ResetRotorOffsetBaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the rotor offsets to base position..
        /// </summary>
        internal static string ResetRotorOffsetBaseTooltip {
            get {
                return ResourceManager.GetString("ResetRotorOffsetBaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null offsets.
        /// </summary>
        internal static string ResetRotorOffsetNullCaption {
            get {
                return ResourceManager.GetString("ResetRotorOffsetNullCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the rotor offsets to 0..
        /// </summary>
        internal static string ResetRotorOffsetNullTooltip {
            get {
                return ResourceManager.GetString("ResetRotorOffsetNullTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base positions.
        /// </summary>
        internal static string ResetRotorOrderCaption {
            get {
                return ResourceManager.GetString("ResetRotorOrderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order the rotors into base positions..
        /// </summary>
        internal static string ResetRotorOrderTooltip {
            get {
                return ResourceManager.GetString("ResetRotorOrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R10.
        /// </summary>
        internal static string Rotor10Caption {
            get {
                return ResourceManager.GetString("Rotor10Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R01.
        /// </summary>
        internal static string Rotor1Caption {
            get {
                return ResourceManager.GetString("Rotor1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R02.
        /// </summary>
        internal static string Rotor2Caption {
            get {
                return ResourceManager.GetString("Rotor2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R03.
        /// </summary>
        internal static string Rotor3Caption {
            get {
                return ResourceManager.GetString("Rotor3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R04.
        /// </summary>
        internal static string Rotor4Caption {
            get {
                return ResourceManager.GetString("Rotor4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R05.
        /// </summary>
        internal static string Rotor5Caption {
            get {
                return ResourceManager.GetString("Rotor5Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R06.
        /// </summary>
        internal static string Rotor6Caption {
            get {
                return ResourceManager.GetString("Rotor6Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R07.
        /// </summary>
        internal static string Rotor7Caption {
            get {
                return ResourceManager.GetString("Rotor7Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R08.
        /// </summary>
        internal static string Rotor8Caption {
            get {
                return ResourceManager.GetString("Rotor8Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R09.
        /// </summary>
        internal static string Rotor9Caption {
            get {
                return ResourceManager.GetString("Rotor9Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core offsets.
        /// </summary>
        internal static string RotorCoreOffsetSelection {
            get {
                return ResourceManager.GetString("RotorCoreOffsetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core order.
        /// </summary>
        internal static string RotorCoreSelection {
            get {
                return ResourceManager.GetString("RotorCoreSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core sides.
        /// </summary>
        internal static string RotorCoreSideSelection {
            get {
                return ResourceManager.GetString("RotorCoreSideSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotor offsets.
        /// </summary>
        internal static string RotorOffsetSelection {
            get {
                return ResourceManager.GetString("RotorOffsetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotor order.
        /// </summary>
        internal static string RotorOrderSelection {
            get {
                return ResourceManager.GetString("RotorOrderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 10..
        /// </summary>
        internal static string RotorRing10OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing10OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 1..
        /// </summary>
        internal static string RotorRing1OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing1OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 2..
        /// </summary>
        internal static string RotorRing2OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing2OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 3..
        /// </summary>
        internal static string RotorRing3OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing3OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 4..
        /// </summary>
        internal static string RotorRing4OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing4OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 5..
        /// </summary>
        internal static string RotorRing5OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing5OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 6..
        /// </summary>
        internal static string RotorRing6OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing6OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 7..
        /// </summary>
        internal static string RotorRing7OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing7OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 8..
        /// </summary>
        internal static string RotorRing8OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing8OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ring offset of rotor  in position 9..
        /// </summary>
        internal static string RotorRing9OffsetTooltip {
            get {
                return ResourceManager.GetString("RotorRing9OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring offsets.
        /// </summary>
        internal static string RotorRingOffsetSelection {
            get {
                return ResourceManager.GetString("RotorRingOffsetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country layout.
        /// </summary>
        internal static string SelectMachineCountryLayoutCaption {
            get {
                return ResourceManager.GetString("SelectMachineCountryLayoutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectd the country layout..
        /// </summary>
        internal static string SelectMachineCountryLayoutTooltip {
            get {
                return ResourceManager.GetString("SelectMachineCountryLayoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard mapping.
        /// </summary>
        internal static string SelectMachineKeyboardMappingCaption {
            get {
                return ResourceManager.GetString("SelectMachineKeyboardMappingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the keyboard mapping..
        /// </summary>
        internal static string SelectMachineKeyboardMappingTooltip {
            get {
                return ResourceManager.GetString("SelectMachineKeyboardMappingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fialka model.
        /// </summary>
        internal static string SelectMachineModelCaption {
            get {
                return ResourceManager.GetString("SelectMachineModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the machine model type..
        /// </summary>
        internal static string SelectMachineModelTooltip {
            get {
                return ResourceManager.GetString("SelectMachineModelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num lock.
        /// </summary>
        internal static string SelectMachineNumLockTypeCaption {
            get {
                return ResourceManager.GetString("SelectMachineNumLockTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the NumLock type..
        /// </summary>
        internal static string SelectMachineNumLockTypeTooltip {
            get {
                return ResourceManager.GetString("SelectMachineNumLockTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation mode.
        /// </summary>
        internal static string SelectMachineOperationModeCaption {
            get {
                return ResourceManager.GetString("SelectMachineOperationModeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the operation mode..
        /// </summary>
        internal static string SelectMachineOperationModeTooltip {
            get {
                return ResourceManager.GetString("SelectMachineOperationModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print head mapping.
        /// </summary>
        internal static string SelectMachinePrintHeadMappingCaption {
            get {
                return ResourceManager.GetString("SelectMachinePrintHeadMappingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the print head mapping..
        /// </summary>
        internal static string SelectMachinePrintHeadMappingTooltip {
            get {
                return ResourceManager.GetString("SelectMachinePrintHeadMappingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text operation mode.
        /// </summary>
        internal static string SelectMachineTxtOpModeCaption {
            get {
                return ResourceManager.GetString("SelectMachineTxtOpModeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the text operation mode for M-125-3 machine. .
        /// </summary>
        internal static string SelectMachineTxtOpModeTooltip {
            get {
                return ResourceManager.GetString("SelectMachineTxtOpModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 10..
        /// </summary>
        internal static string SelectRotor10CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor10CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 10..
        /// </summary>
        internal static string SelectRotor10CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor10CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 10..
        /// </summary>
        internal static string SelectRotor10OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor10OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 10..
        /// </summary>
        internal static string SelectRotor10OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor10OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 1..
        /// </summary>
        internal static string SelectRotor1CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor1CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 1..
        /// </summary>
        internal static string SelectRotor1CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor1CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 1..
        /// </summary>
        internal static string SelectRotor1OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor1OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 1..
        /// </summary>
        internal static string SelectRotor1OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor1OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 2..
        /// </summary>
        internal static string SelectRotor2CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor2CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 2..
        /// </summary>
        internal static string SelectRotor2CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor2CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 2..
        /// </summary>
        internal static string SelectRotor2OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor2OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 2..
        /// </summary>
        internal static string SelectRotor2OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor2OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 3..
        /// </summary>
        internal static string SelectRotor3CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor3CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 3..
        /// </summary>
        internal static string SelectRotor3CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor3CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 3..
        /// </summary>
        internal static string SelectRotor3OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor3OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 3..
        /// </summary>
        internal static string SelectRotor3OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor3OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 4..
        /// </summary>
        internal static string SelectRotor4CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor4CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 4..
        /// </summary>
        internal static string SelectRotor4CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor4CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 4..
        /// </summary>
        internal static string SelectRotor4OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor4OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 4..
        /// </summary>
        internal static string SelectRotor4OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor4OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 5..
        /// </summary>
        internal static string SelectRotor5CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor5CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 5..
        /// </summary>
        internal static string SelectRotor5CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor5CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 5..
        /// </summary>
        internal static string SelectRotor5OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor5OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 5..
        /// </summary>
        internal static string SelectRotor5OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor5OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 6..
        /// </summary>
        internal static string SelectRotor6CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor6CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 6..
        /// </summary>
        internal static string SelectRotor6CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor6CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 6..
        /// </summary>
        internal static string SelectRotor6OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor6OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 6..
        /// </summary>
        internal static string SelectRotor6OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor6OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 7..
        /// </summary>
        internal static string SelectRotor7CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor7CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 7..
        /// </summary>
        internal static string SelectRotor7CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor7CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 7..
        /// </summary>
        internal static string SelectRotor7OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor7OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 7..
        /// </summary>
        internal static string SelectRotor7OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor7OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 8..
        /// </summary>
        internal static string SelectRotor8CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor8CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 8..
        /// </summary>
        internal static string SelectRotor8CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor8CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 8..
        /// </summary>
        internal static string SelectRotor8OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor8OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 8..
        /// </summary>
        internal static string SelectRotor8OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor8OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of core 9..
        /// </summary>
        internal static string SelectRotor9CoreOffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor9CoreOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the side of core 9..
        /// </summary>
        internal static string SelectRotor9CoreSideTooltip {
            get {
                return ResourceManager.GetString("SelectRotor9CoreSideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the offset of rotor in position 9..
        /// </summary>
        internal static string SelectRotor9OffsetTooltip {
            get {
                return ResourceManager.GetString("SelectRotor9OffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order (position in drum from left) of rotor 9..
        /// </summary>
        internal static string SelectRotor9OrderTooltip {
            get {
                return ResourceManager.GetString("SelectRotor9OrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 10 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore10Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore10Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 1 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore1Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 2 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore2Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 3 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore3Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore3Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 4 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore4Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore4Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 5 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore5Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore5Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 6 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore6Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore6Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 7 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore7Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore7Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 8 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore8Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore8Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position of core 9 (position in rotors in the drum)..
        /// </summary>
        internal static string SelectRotorCore9Tooltip {
            get {
                return ResourceManager.GetString("SelectRotorCore9Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotor series.
        /// </summary>
        internal static string SelectRotorSeriesCaption {
            get {
                return ResourceManager.GetString("SelectRotorSeriesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the country specific rotor series..
        /// </summary>
        internal static string SelectRotorSeriesTooltip {
            get {
                return ResourceManager.GetString("SelectRotorSeriesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotor type.
        /// </summary>
        internal static string SelectRotorTypesCaption {
            get {
                return ResourceManager.GetString("SelectRotorTypesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the rotor type..
        /// </summary>
        internal static string SelectRotorTypesTooltip {
            get {
                return ResourceManager.GetString("SelectRotorTypesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input handling.
        /// </summary>
        internal static string SettingsInputhandlerCaption {
            get {
                return ResourceManager.GetString("SettingsInputhandlerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How will the invalid input displayed..
        /// </summary>
        internal static string SettingsInputhandlerTooltip {
            get {
                return ResourceManager.GetString("SettingsInputhandlerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output will update.
        /// </summary>
        internal static string SettingsOutputUpdateCaption {
            get {
                return ResourceManager.GetString("SettingsOutputUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select when will the output updated..
        /// </summary>
        internal static string SettingsOutputUpdateTooltip {
            get {
                return ResourceManager.GetString("SettingsOutputUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore initial key .
        /// </summary>
        internal static string SettingsRestoreCaption {
            get {
                return ResourceManager.GetString("SettingsRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When will the initial key (set before encryption) restored in workflow..
        /// </summary>
        internal static string SettingsRestoreTooltip {
            get {
                return ResourceManager.GetString("SettingsRestoreTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide settings.
        /// </summary>
        internal static string VisibilityCaption {
            get {
                return ResourceManager.GetString("VisibilityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / hide the elements in this group..
        /// </summary>
        internal static string VisibilityTooltip {
            get {
                return ResourceManager.GetString("VisibilityTooltip", resourceCulture);
            }
        }
    }
}
