//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptool.Plugins.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptool.Plugins.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additions.
        /// </summary>
        internal static string _Additions {
            get {
                return ResourceManager.GetString("_Additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string _Bonus {
            get {
                return ResourceManager.GetString("_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp.
        /// </summary>
        internal static string _Comp {
            get {
                return ResourceManager.GetString("_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity.
        /// </summary>
        internal static string _Complexity {
            get {
                return ResourceManager.GetString("_Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cond.
        /// </summary>
        internal static string _Cond {
            get {
                return ResourceManager.GetString("_Cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cond / Incr.
        /// </summary>
        internal static string _Cond_Incr {
            get {
                return ResourceManager.GetString("_Cond_Incr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Lowercase Letters.
        /// </summary>
        internal static string _Consecutive_Lowercase_Letters {
            get {
                return ResourceManager.GetString("_Consecutive_Lowercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Numbers.
        /// </summary>
        internal static string _Consecutive_Numbers {
            get {
                return ResourceManager.GetString("_Consecutive_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Uppercase Letters.
        /// </summary>
        internal static string _Consecutive_Uppercase_Letters {
            get {
                return ResourceManager.GetString("_Consecutive_Uppercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string _Count {
            get {
                return ResourceManager.GetString("_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions.
        /// </summary>
        internal static string _Dedutcions {
            get {
                return ResourceManager.GetString("_Dedutcions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        internal static string _Flat {
            get {
                return ResourceManager.GetString("_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string _Good {
            get {
                return ResourceManager.GetString("_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters Only.
        /// </summary>
        internal static string _Letters_Only {
            get {
                return ResourceManager.GetString("_Letters_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase Letters.
        /// </summary>
        internal static string _Lowercase_Letters {
            get {
                return ResourceManager.GetString("_Lowercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Numbers or Symbols.
        /// </summary>
        internal static string _Middle_Numbers_or_Symbols {
            get {
                return ResourceManager.GetString("_Middle_Numbers_or_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Characters.
        /// </summary>
        internal static string _Number_of_Characters {
            get {
                return ResourceManager.GetString("_Number_of_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        internal static string _Numbers {
            get {
                return ResourceManager.GetString("_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers Only.
        /// </summary>
        internal static string _Numbers_Only {
            get {
                return ResourceManager.GetString("_Numbers_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string _Rate {
            get {
                return ResourceManager.GetString("_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Characters Case Insensitive.
        /// </summary>
        internal static string _Repeat_Characters_Case_Insensitive {
            get {
                return ResourceManager.GetString("_Repeat_Characters_Case_Insensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        internal static string _Requirements {
            get {
                return ResourceManager.GetString("_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string _Score {
            get {
                return ResourceManager.GetString("_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Letters.
        /// </summary>
        internal static string _Sequential_Letters {
            get {
                return ResourceManager.GetString("_Sequential_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Numbers.
        /// </summary>
        internal static string _Sequential_Numbers {
            get {
                return ResourceManager.GetString("_Sequential_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Symbols.
        /// </summary>
        internal static string _Sequential_Symbols {
            get {
                return ResourceManager.GetString("_Sequential_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string _Strong {
            get {
                return ResourceManager.GetString("_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string _Symbols {
            get {
                return ResourceManager.GetString("_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase Letters.
        /// </summary>
        internal static string _Uppercase_Letters {
            get {
                return ResourceManager.GetString("_Uppercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Strong.
        /// </summary>
        internal static string _VeryStrong {
            get {
                return ResourceManager.GetString("_VeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Weak.
        /// </summary>
        internal static string _VeryWeak {
            get {
                return ResourceManager.GetString("_VeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        internal static string _Weak {
            get {
                return ResourceManager.GetString("_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password which shall be tested.
        /// </summary>
        internal static string PasswordTooltip {
            get {
                return ResourceManager.GetString("PasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordStrength.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool to check the strength of passwords.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string StrengthCaption {
            get {
                return ResourceManager.GetString("StrengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strength of the entered password..
        /// </summary>
        internal static string StrengthTooltip {
            get {
                return ResourceManager.GetString("StrengthTooltip", resourceCulture);
            }
        }
    }
}
