//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextOutput.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextOutput.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append n-breaks ähnelt.
        /// </summary>
        internal static string AppendBreaksCaption {
            get {
                return ResourceManager.GetString("AppendBreaksCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defines how much new lines are added after new input. (Applies only if &quot;Append text input&quot; is active.) ähnelt.
        /// </summary>
        internal static string AppendBreaksTooltip {
            get {
                return ResourceManager.GetString("AppendBreaksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append text input ähnelt.
        /// </summary>
        internal static string AppendCaption {
            get {
                return ResourceManager.GetString("AppendCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append ähnelt.
        /// </summary>
        internal static string AppendGroup {
            get {
                return ResourceManager.GetString("AppendGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append text input ähnelt.
        /// </summary>
        internal static string AppendList1 {
            get {
                return ResourceManager.GetString("AppendList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With this checkbox enabled, incoming text will be appended to the current text. ähnelt.
        /// </summary>
        internal static string AppendTooltip {
            get {
                return ResourceManager.GetString("AppendTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display boolean as numeric value ähnelt.
        /// </summary>
        internal static string BooleanAsNumericCaption {
            get {
                return ResourceManager.GetString("BooleanAsNumericCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display boolean as numeric value ähnelt.
        /// </summary>
        internal static string BooleanAsNumericList1 {
            get {
                return ResourceManager.GetString("BooleanAsNumericList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With this checkbox enabled, incoming boolean values will be displayed as numeric values (1/0 instead of True/False). ähnelt.
        /// </summary>
        internal static string BooleanAsNumericTooltip {
            get {
                return ResourceManager.GetString("BooleanAsNumericTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        internal static string DataTypeCaption {
            get {
                return ResourceManager.GetString("DataTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select DataType of plugin. ähnelt.
        /// </summary>
        internal static string DataTypeTooltip {
            get {
                return ResourceManager.GetString("DataTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input encoding ähnelt.
        /// </summary>
        internal static string EncodingSettingCaption {
            get {
                return ResourceManager.GetString("EncodingSettingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default system encoding ähnelt.
        /// </summary>
        internal static string EncodingSettingList1 {
            get {
                return ResourceManager.GetString("EncodingSettingList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unicode ähnelt.
        /// </summary>
        internal static string EncodingSettingList2 {
            get {
                return ResourceManager.GetString("EncodingSettingList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UTF-7 ähnelt.
        /// </summary>
        internal static string EncodingSettingList3 {
            get {
                return ResourceManager.GetString("EncodingSettingList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UTF-8 ähnelt.
        /// </summary>
        internal static string EncodingSettingList4 {
            get {
                return ResourceManager.GetString("EncodingSettingList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UTF-32 ähnelt.
        /// </summary>
        internal static string EncodingSettingList5 {
            get {
                return ResourceManager.GetString("EncodingSettingList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ASCII ähnelt.
        /// </summary>
        internal static string EncodingSettingList6 {
            get {
                return ResourceManager.GetString("EncodingSettingList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big endian unicode ähnelt.
        /// </summary>
        internal static string EncodingSettingList7 {
            get {
                return ResourceManager.GetString("EncodingSettingList7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the expected encoding of the input. ähnelt.
        /// </summary>
        internal static string EncodingSettingTooltip {
            get {
                return ResourceManager.GetString("EncodingSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input encoding ähnelt.
        /// </summary>
        internal static string EncodingSettingTPCaption {
            get {
                return ResourceManager.GetString("EncodingSettingTPCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the expected encoding of the input. (The input will be interpreted as set here, no matter what the bytes really mean) ähnelt.
        /// </summary>
        internal static string EncodingSettingTPTooltip {
            get {
                return ResourceManager.GetString("EncodingSettingTPTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flush text on PreExec ähnelt.
        /// </summary>
        internal static string FlushOnPreExecutionCaption {
            get {
                return ResourceManager.GetString("FlushOnPreExecutionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flush text on PreExec ähnelt.
        /// </summary>
        internal static string FlushOnPreExecutionList1 {
            get {
                return ResourceManager.GetString("FlushOnPreExecutionList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flush all text boxes on PreExecution call. ähnelt.
        /// </summary>
        internal static string FlushOnPreExecutionTooltip {
            get {
                return ResourceManager.GetString("FlushOnPreExecutionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum length ähnelt.
        /// </summary>
        internal static string MaxLengthCaption {
            get {
                return ResourceManager.GetString("MaxLengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provide the maximum number of bytes to convert. ähnelt.
        /// </summary>
        internal static string MaxLengthTooltip {
            get {
                return ResourceManager.GetString("MaxLengthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TextOutput ähnelt.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string PluginDescriptionURL {
            get {
                return ResourceManager.GetString("PluginDescriptionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple text output ähnelt.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presentation format ähnelt.
        /// </summary>
        internal static string PresentationFormatSettingCaption {
            get {
                return ResourceManager.GetString("PresentationFormatSettingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        internal static string PresentationFormatSettingList1 {
            get {
                return ResourceManager.GetString("PresentationFormatSettingList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hex ähnelt.
        /// </summary>
        internal static string PresentationFormatSettingList2 {
            get {
                return ResourceManager.GetString("PresentationFormatSettingList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base64 ähnelt.
        /// </summary>
        internal static string PresentationFormatSettingList3 {
            get {
                return ResourceManager.GetString("PresentationFormatSettingList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decimal ähnelt.
        /// </summary>
        internal static string PresentationFormatSettingList4 {
            get {
                return ResourceManager.GetString("PresentationFormatSettingList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the format that will be used to present the input data. ähnelt.
        /// </summary>
        internal static string PresentationFormatSettingTooltip {
            get {
                return ResourceManager.GetString("PresentationFormatSettingTooltip", resourceCulture);
            }
        }
    }
}
