//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptool.VigenereAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptool.VigenereAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciphertext.
        /// </summary>
        public static string CiphertextCaption {
            get {
                return ResourceManager.GetString("CiphertextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ciphertext that should be analyzed..
        /// </summary>
        public static string CiphertextTooltip {
            get {
                return ResourceManager.GetString("CiphertextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all lines.
        /// </summary>
        public static string Copy_all {
            get {
                return ResourceManager.GetString("Copy_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy key.
        /// </summary>
        public static string Copy_key {
            get {
                return ResourceManager.GetString("Copy_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected line.
        /// </summary>
        public static string Copy_line {
            get {
                return ResourceManager.GetString("Copy_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        public static string Copy_text {
            get {
                return ResourceManager.GetString("Copy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy value.
        /// </summary>
        public static string Copy_value {
            get {
                return ResourceManager.GetString("Copy_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current analyzed keylength:.
        /// </summary>
        public static string CurrentAnalysedKeylengthLabel {
            get {
                return ResourceManager.GetString("CurrentAnalysedKeylengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time:.
        /// </summary>
        public static string ElapsedLabel {
            get {
                return ResourceManager.GetString("ElapsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        public static string EndLabel {
            get {
                return ResourceManager.GetString("EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse from Keylength.
        /// </summary>
        public static string FromKeylengthCaption {
            get {
                return ResourceManager.GetString("FromKeylengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse the given Ciphertext and start from this keylength..
        /// </summary>
        public static string FromKeylengthTooltip {
            get {
                return ResourceManager.GetString("FromKeylengthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greedy.
        /// </summary>
        public static string GreedyCaption {
            get {
                return ResourceManager.GetString("GreedyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do a greedy hillclimbing or not..
        /// </summary>
        public static string GreedyTooltip {
            get {
                return ResourceManager.GetString("GreedyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Key.
        /// </summary>
        public static string KeyCaption {
            get {
                return ResourceManager.GetString("KeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string KeyHeader {
            get {
                return ResourceManager.GetString("KeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Length.
        /// </summary>
        public static string KeyLengthHeader {
            get {
                return ResourceManager.GetString("KeyLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keystyle.
        /// </summary>
        public static string KeyStyleCaption {
            get {
                return ResourceManager.GetString("KeyStyleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the key a natural passphrase or not?.
        /// </summary>
        public static string KeyStyleTooltip {
            get {
                return ResourceManager.GetString("KeyStyleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best key found during the analysis..
        /// </summary>
        public static string KeyTooltip {
            get {
                return ResourceManager.GetString("KeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageCaption {
            get {
                return ResourceManager.GetString("LanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this language for the quadgram scoring..
        /// </summary>
        public static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ModeCaption {
            get {
                return ResourceManager.GetString("ModeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this mode for the analysis..
        /// </summary>
        public static string ModeTooltip {
            get {
                return ResourceManager.GetString("ModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Language.
        /// </summary>
        public static string NaturalLanguage {
            get {
                return ResourceManager.GetString("NaturalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Plaintext.
        /// </summary>
        public static string PlaintextCaption {
            get {
                return ResourceManager.GetString("PlaintextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best plaintext which was found during the analysis..
        /// </summary>
        public static string PlaintextTooltip {
            get {
                return ResourceManager.GetString("PlaintextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigenère Analyzer.
        /// </summary>
        public static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptanalysis of the Vigenère cipher using hillclimbing..
        /// </summary>
        public static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts.
        /// </summary>
        public static string RestartsCaption {
            get {
                return ResourceManager.GetString("RestartsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of restarts of the hillclimbing algorithm..
        /// </summary>
        public static string RestartsTooltip {
            get {
                return ResourceManager.GetString("RestartsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextHeader {
            get {
                return ResourceManager.GetString("TextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse to Keylength.
        /// </summary>
        public static string ToKeylengthCaption {
            get {
                return ResourceManager.GetString("ToKeylengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse the given Ciphertext and stop including this keylength..
        /// </summary>
        public static string ToKeylengthTooltip {
            get {
                return ResourceManager.GetString("ToKeylengthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueHeader {
            get {
                return ResourceManager.GetString("ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Vigenère.
        /// </summary>
        public static string Vigenere {
            get {
                return ResourceManager.GetString("Vigenere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigenère Alphabet.
        /// </summary>
        public static string VigenereAlphabetCaption {
            get {
                return ResourceManager.GetString("VigenereAlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this Vigenère alphabet for the analyis..
        /// </summary>
        public static string VigenereAlphabetTooltip {
            get {
                return ResourceManager.GetString("VigenereAlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigenère Autokey.
        /// </summary>
        public static string VigenereAutokey {
            get {
                return ResourceManager.GetString("VigenereAutokey", resourceCulture);
            }
        }
    }
}
