using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Cryptool.MD5
{
    public enum Md5State
    {
        UNINITIALIZED, INITIALIZED,
        READING_DATA, READ_DATA,
        STARTING_PADDING, ADDING_PADDING_BYTES, ADDED_PADDING_BYTES, ADDING_LENGTH, ADDED_LENGTH, FINISHED_PADDING,
        STARTING_COMPRESSION, STARTING_ROUND, STARTING_ROUND_STEP, FINISHED_ROUND_STEP, FINISHED_ROUND, FINISHING_COMPRESSION, FINISHED_COMPRESSION,
        FINISHED
    }
}
