//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primes.Resources.lang.WpfControls.Distribution {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Distribution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Distribution() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primes.Resources.lang.WpfControls.Distribution.Distribution", typeof(Distribution).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string graph_btnResume {
            get {
                return ResourceManager.GetString("graph_btnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string graph_btnStop {
            get {
                return ResourceManager.GetString("graph_btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string graph_contextmenucopy {
            get {
                return ResourceManager.GetString("graph_contextmenucopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of primes according to the Prime Number Theorem:.
        /// </summary>
        public static string graph_gausscountinfo {
            get {
                return ResourceManager.GetString("graph_gausscountinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating the number of primes according to the Prime Number Theorem:.
        /// </summary>
        public static string graph_gausscountinfoCalculating {
            get {
                return ResourceManager.GetString("graph_gausscountinfoCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Number Theorem.
        /// </summary>
        public static string graph_gaussname {
            get {
                return ResourceManager.GetString("graph_gaussname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available functions for calculating the number of primes Y in a given range X.
        /// </summary>
        public static string graph_groupboxheader {
            get {
                return ResourceManager.GetString("graph_groupboxheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of primes according to the logarithmic integral:.
        /// </summary>
        public static string graph_lincountinfo {
            get {
                return ResourceManager.GetString("graph_lincountinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating the number of primes according to the logarithmic integral:.
        /// </summary>
        public static string graph_lincountinfoCalculating {
            get {
                return ResourceManager.GetString("graph_lincountinfoCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logarithmic integral.
        /// </summary>
        public static string graph_linname {
            get {
                return ResourceManager.GetString("graph_linname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual number of primes is:.
        /// </summary>
        public static string graph_pincountinfo {
            get {
                return ResourceManager.GetString("graph_pincountinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calclulating the actual number of primes:.
        /// </summary>
        public static string graph_pincountinfoCalculating {
            get {
                return ResourceManager.GetString("graph_pincountinfoCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact step function π.
        /// </summary>
        public static string graph_pinname {
            get {
                return ResourceManager.GetString("graph_pinname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference between &quot;from&quot; and &quot;to&quot; must be at least {0}..
        /// </summary>
        public static string graph_validatorrangemessage {
            get {
                return ResourceManager.GetString("graph_validatorrangemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current number.
        /// </summary>
        public static string numbergrid_actualnumber {
            get {
                return ResourceManager.GetString("numbergrid_actualnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string numbergrid_btnExecute {
            get {
                return ResourceManager.GetString("numbergrid_btnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string numbergrid_height {
            get {
                return ResourceManager.GetString("numbergrid_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string numbergrid_input {
            get {
                return ResourceManager.GetString("numbergrid_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll rowwise in the number grid.
        /// </summary>
        public static string numbergrid_scroll {
            get {
                return ResourceManager.GetString("numbergrid_scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string numbergrid_start {
            get {
                return ResourceManager.GetString("numbergrid_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to scroll down one row..
        /// </summary>
        public static string numbergrid_tooltipscrolldown {
            get {
                return ResourceManager.GetString("numbergrid_tooltipscrolldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to scroll down two rows..
        /// </summary>
        public static string numbergrid_tooltipscrolldownfast {
            get {
                return ResourceManager.GetString("numbergrid_tooltipscrolldownfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to scroll up one row..
        /// </summary>
        public static string numbergrid_tooltipscrollup {
            get {
                return ResourceManager.GetString("numbergrid_tooltipscrollup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to scroll up two rows..
        /// </summary>
        public static string numbergrid_tooltipscrollupfast {
            get {
                return ResourceManager.GetString("numbergrid_tooltipscrollupfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string numbergrid_width {
            get {
                return ResourceManager.GetString("numbergrid_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom the number grid.
        /// </summary>
        public static string numbergrid_zoom {
            get {
                return ResourceManager.GetString("numbergrid_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current number n =.
        /// </summary>
        public static string numberline_actualnumber {
            get {
                return ResourceManager.GetString("numberline_actualnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (calculating).
        /// </summary>
        public static string numberline_calculating {
            get {
                return ResourceManager.GetString("numberline_calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel calculations.
        /// </summary>
        public static string numberline_cancelcalculations {
            get {
                return ResourceManager.GetString("numberline_cancelcalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of primes according to the estimate of Gauss&apos; prime number theorem is {0}..
        /// </summary>
        public static string numberline_countprimesgauss {
            get {
                return ResourceManager.GetString("numberline_countprimesgauss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual number of primes in this range is {0}..
        /// </summary>
        public static string numberline_countprimespin {
            get {
                return ResourceManager.GetString("numberline_countprimespin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of divisors.
        /// </summary>
        public static string numberline_divcount {
            get {
                return ResourceManager.GetString("numberline_divcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of the divisors.
        /// </summary>
        public static string numberline_divsum {
            get {
                return ResourceManager.GetString("numberline_divsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler&apos;s φ-function.
        /// </summary>
        public static string numberline_eulerphi {
            get {
                return ResourceManager.GetString("numberline_eulerphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} coprime numbers for the current number {1}..
        /// </summary>
        public static string numberline_eulerphifoundresult {
            get {
                return ResourceManager.GetString("numberline_eulerphifoundresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a prime. Therefore the number of coprime numbers to {1} is {2} - 1 = {3}..
        /// </summary>
        public static string numberline_eulerphiisprime {
            get {
                return ResourceManager.GetString("numberline_eulerphiisprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the first {0} of {1} values are displayed..
        /// </summary>
        public static string numberline_eulerphimaxlines {
            get {
                return ResourceManager.GetString("numberline_eulerphimaxlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of divisor totients.
        /// </summary>
        public static string numberline_eulerphisum {
            get {
                return ResourceManager.GetString("numberline_eulerphisum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the current number {0} the formula evaluates to {1}..
        /// </summary>
        public static string numberline_eulerphisuminfo {
            get {
                return ResourceManager.GetString("numberline_eulerphisuminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to φ({0}) = {1}.
        /// </summary>
        public static string numberline_eulerphisumlog {
            get {
                return ResourceManager.GetString("numberline_eulerphisumlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorization.
        /// </summary>
        public static string numberline_factorization {
            get {
                return ResourceManager.GetString("numberline_factorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (calculating factorization).
        /// </summary>
        public static string numberline_factorizationcalculating {
            get {
                return ResourceManager.GetString("numberline_factorizationcalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string numberline_from {
            get {
                return ResourceManager.GetString("numberline_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldbach&apos;s conjecture.
        /// </summary>
        public static string numberline_goldbach {
            get {
                return ResourceManager.GetString("numberline_goldbach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} prime number sum for the current number {1}..
        /// </summary>
        public static string numberline_goldbachfoundsum {
            get {
                return ResourceManager.GetString("numberline_goldbachfoundsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} prime number sums for the current number {1}..
        /// </summary>
        public static string numberline_goldbachfoundsums {
            get {
                return ResourceManager.GetString("numberline_goldbachfoundsums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Every even number &gt; 2 can be expressed as a sum of 2 prime numbers.).
        /// </summary>
        public static string numberline_goldbachinfo {
            get {
                return ResourceManager.GetString("numberline_goldbachinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the first {0} sums are displayed..
        /// </summary>
        public static string numberline_goldbachmaxlines {
            get {
                return ResourceManager.GetString("numberline_goldbachmaxlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move with the mouse along the number line to get number-theoretic statements of the selected number. The number line acts as a sliding window over the integers with a display range between 10 to 90 numbers. You can adjust the range with the slider, which determines the upper limit of the range..
        /// </summary>
        public static string numberline_header {
            get {
                return ResourceManager.GetString("numberline_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of primes in the selected range.
        /// </summary>
        public static string numberline_headercoutprimes {
            get {
                return ResourceManager.GetString("numberline_headercoutprimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lies inside the prime twins ({1}, {2})..
        /// </summary>
        public static string numberline_insidetwinprime {
            get {
                return ResourceManager.GetString("numberline_insidetwinprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Goldbach conjecture only holds for even numbers. {0} is odd..
        /// </summary>
        public static string numberline_isodd {
            get {
                return ResourceManager.GetString("numberline_isodd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is prime.
        /// </summary>
        public static string numberline_isprime {
            get {
                return ResourceManager.GetString("numberline_isprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, {1}, {2}, {3}) is a prime quadruplet..
        /// </summary>
        public static string numberline_isquadtrupletprime {
            get {
                return ResourceManager.GetString("numberline_isquadtrupletprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, {1}, {2}, {3}, {4}, {5}) is a prime sixtuplet..
        /// </summary>
        public static string numberline_issixtupletprime {
            get {
                return ResourceManager.GetString("numberline_issixtupletprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, {1}) is a prime twin..
        /// </summary>
        public static string numberline_istwinprime {
            get {
                return ResourceManager.GetString("numberline_istwinprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Goldbach conjecture only holds for even numbers &gt; 2..
        /// </summary>
        public static string numberline_istwo {
            get {
                return ResourceManager.GetString("numberline_istwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower boundary of the interval is 2, the upper boundary is 10^9. With the arrow keys, you can move left and right through the interval in steps of size 1 or 10..
        /// </summary>
        public static string numberline_maxinterval {
            get {
                return ResourceManager.GetString("numberline_maxinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next bigger prime number.
        /// </summary>
        public static string numberline_nextprime {
            get {
                return ResourceManager.GetString("numberline_nextprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next bigger prime twin is ({0}, {1})..
        /// </summary>
        public static string numberline_nexttwinprime {
            get {
                return ResourceManager.GetString("numberline_nexttwinprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of primes in the selected range ({0}, {1}).
        /// </summary>
        public static string numberline_numberofprimeinterval {
            get {
                return ResourceManager.GetString("numberline_numberofprimeinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of primes &lt;= n.
        /// </summary>
        public static string numberline_numberofprimes {
            get {
                return ResourceManager.GetString("numberline_numberofprimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of points displayed.
        /// </summary>
        public static string numberline_pointsdisplayed {
            get {
                return ResourceManager.GetString("numberline_pointsdisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next smaller prime number.
        /// </summary>
        public static string numberline_priorprime {
            get {
                return ResourceManager.GetString("numberline_priorprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next smaller prime twin is ({0}, {1})..
        /// </summary>
        public static string numberline_priortwinprime {
            get {
                return ResourceManager.GetString("numberline_priortwinprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string numberline_progress {
            get {
                return ResourceManager.GetString("numberline_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime quadruplets.
        /// </summary>
        public static string numberline_quadtuplet {
            get {
                return ResourceManager.GetString("numberline_quadtuplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the divisors of the current number {0} is {1}..
        /// </summary>
        public static string numberline_rhoinfo {
            get {
                return ResourceManager.GetString("numberline_rhoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime sixtuplets.
        /// </summary>
        public static string numberline_sixtuplet {
            get {
                return ResourceManager.GetString("numberline_sixtuplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} divisors for the current number {1}..
        /// </summary>
        public static string numberline_tauinfo {
            get {
                return ResourceManager.GetString("numberline_tauinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string numberline_to {
            get {
                return ResourceManager.GetString("numberline_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce range to at least 10 numbers.
        /// </summary>
        public static string numberline_tooltipdecrange {
            get {
                return ResourceManager.GetString("numberline_tooltipdecrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase range to at most 90 numbers.
        /// </summary>
        public static string numberline_tooltipincrange {
            get {
                return ResourceManager.GetString("numberline_tooltipincrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce range in increments of 1.
        /// </summary>
        public static string numberline_tooltipscrollleft {
            get {
                return ResourceManager.GetString("numberline_tooltipscrollleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce range in increments of 10.
        /// </summary>
        public static string numberline_tooltipscrollleftfast {
            get {
                return ResourceManager.GetString("numberline_tooltipscrollleftfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase range in increments of 1.
        /// </summary>
        public static string numberline_tooltipscrollright {
            get {
                return ResourceManager.GetString("numberline_tooltipscrollright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase range in increments of 10.
        /// </summary>
        public static string numberline_tooltipscrollrightfast {
            get {
                return ResourceManager.GetString("numberline_tooltipscrollrightfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime twins.
        /// </summary>
        public static string numberline_twinprime {
            get {
                return ResourceManager.GetString("numberline_twinprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of primes.
        /// </summary>
        public static string tabitemgraph {
            get {
                return ResourceManager.GetString("tabitemgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number grid.
        /// </summary>
        public static string tabitemnumbergrid {
            get {
                return ResourceManager.GetString("tabitemnumbergrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number line.
        /// </summary>
        public static string tabitemnumberline {
            get {
                return ResourceManager.GetString("tabitemnumberline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulam&apos;s spiral.
        /// </summary>
        public static string tabitemulam {
            get {
                return ResourceManager.GetString("tabitemulam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ulam_btnCancel {
            get {
                return ResourceManager.GetString("ulam_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string ulam_btnExecute {
            get {
                return ResourceManager.GetString("ulam_btnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating the spiral .
        /// </summary>
        public static string ulam_calculating {
            get {
                return ResourceManager.GetString("ulam_calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning and end of the spiral.
        /// </summary>
        public static string ulam_input {
            get {
                return ResourceManager.GetString("ulam_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the spiral.
        /// </summary>
        public static string ulam_rotate {
            get {
                return ResourceManager.GetString("ulam_rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference between &quot;from&quot; and &quot;to&quot; must be at least {0} and at most {1}..
        /// </summary>
        public static string ulam_validatorrangemessage {
            get {
                return ResourceManager.GetString("ulam_validatorrangemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom the spiral.
        /// </summary>
        public static string ulam_zoom {
            get {
                return ResourceManager.GetString("ulam_zoom", resourceCulture);
            }
        }
    }
}
