package common;

public enum Flag {
    RESOURCE_PATH,
    CIPHERTEXT,
    CRIB,
    SIMULATION_TEXT_LENGTH,
    THREADS,
    OFFSET,
    CYCLES,
    MODEL,
    SIMULATION,
    VERSION,
    LANGUAGE,
    SIMULATION_OVERLAPS,
    INDICATORS_FILE,
    KEY,
    MODE,
    CRIB_POSITION,
    VERBOSE,
    MESSAGE_INDICATOR,
    RIGHT_ROTOR_SAMPLING,
    MIDDLE_RING_SCOPE,
    HC_SA_CYCLES,
    SCENARIO,
    SCENARIO_PATH,

}
